spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 1347006947@qq.com
    password: gfsbfpbzkmphfdjf
    smtp:
      timeout: 10000
      connectiontimeout: 10000
      writetimeout: 10000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
#    password: 123456
    password: huangpei120
    username: root
    url: jdbc:mysql://39.108.220.199:3306/lost_found?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=UTF-8

server:
  port: 8000
  ssl:
    key-store: classpath:3516603_xyzliu.cn.pfx
    key-store-password: 9SUchh4M
    key-store-type: PKCS12

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  type-aliases-package: com.lost_found.pojo
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




